# Generated by Django 5.0.3 on 2024-04-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='News',
        ),
    ]
