# Generated by Django 5.0.3 on 2024-04-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
