# Generated by Django 5.0.3 on 2024-04-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_updatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='update_count',
            field=models.IntegerField(default=0),
        ),
    ]
