# Generated by Django 5.0.3 on 2024-04-13 08:05

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_new_update_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatehistory',
            old_name='update_details',
            new_name='description_after',
        ),
        migrations.AddField(
            model_name='updatehistory',
            name='description_before',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatehistory',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.images_directory_path, validators=[news.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='updatehistory',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.images_directory_path, validators=[news.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='updatehistory',
            name='title_after',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='updatehistory',
            name='title_before',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
