# Generated by Django 5.0.3 on 2024-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
