# Generated by Django 5.0.3 on 2024-04-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_new_is_published_delete_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatehistory',
            name='previous_update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
