# Generated by Django 5.0.4 on 2024-05-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EachComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('composition_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.compositionunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='each_compositions',
            field=models.ManyToManyField(blank=True, to='product.eachcomposition'),
        ),
    ]
