# Generated by Django 5.0.4 on 2024-05-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='slug',
        ),
    ]
