# Generated by Django 5.0.4 on 2024-05-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsize',
            name='value',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
