# Generated by Django 5.0.3 on 2024-04-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Drug',
        ),
    ]
