# Generated by Django 5.0.3 on 2024-04-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_drug_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
