# Generated by Django 5.0.4 on 2024-05-09 15:22

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.images_directory_path, validators=[gallery.models.validate_file_extension]),
        ),
    ]
